###
# Get all employees
GET http://localhost:3000/api/employees HTTP/1.1

###
# Get a existing employee by uid
GET http://localhost:3000/api/employees/6504dhHgedMPc86NgQMvRm1URkQ2 HTTP/1.1

###
# Get a existing employee by name
GET http://localhost:3000/api/employees/by-name/Modric HTTP/1.1

###
# Get a existing employee by cedula
GET http://localhost:3000/api/employees/by-cedula/787212 HTTP/1.1


###
# Get by email and password
POST http://localhost:3000/api/employees/login HTTP/1.1
content-type: application/json
 body: JSON.stringify({
            email: email,
            password: password,
          }),


###
# Delete a existing employee
DELETE http://localhost:3000/api/employees/6504dhHgedMPc86NgQMvRm1URkQ2 HTTP/1.1